### ISSUE TITLE
Erro interno do package

### ISSUE THREAD

**Issue by Mateusvaz89** [marcobraghim/sigepweb#3]
E/flutter (10656): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: Erro interno do package. Por favor considere abrir uma questão em https://github.com/marcobraghim/sigepweb/issues
E/flutter (10656): Mensagem da exception foi: DioError [DioErrorType.DEFAULT]: Bad state: Insecure HTTP is not allowed by platform: http://ws.correios.com.br/calculador/CalcPrecoPrazo.asmx/CalcPrecoPrazo?nCdEmpresa=08082650&sDsSenha=564321&nCdServico=04014%2C04510&sCepOrigem=66053180&sCepDestino=68680000&nVlPeso=0.1&nCdFormato=1&nVlComprimento=16&nVlAltura=12&nVlLargura=16&nVlDiametro=0&sCdMaoPropria=N&nVlValorDeclarado=0.0&sCdAvisoRecebimento=S&StrRetorno=xml&nIndicaCalculo=3
E/flutter (10656): #0      _HttpClient._openUrl (dart:_http/http_impl.dart:2434:7)
E/flutter (10656): #1      _HttpClient.openUrl (dart:_http/http_impl.dart:2341:7)
E/flutter (10656): #2      DefaultHttpClientAdapter.fetch (package:dio/src/adapters/io_adapter.dart:35:40)
E/flutter (10656): #3      DioMixin._dispatchRequest (package:dio/src/dio.dart:923:46)
E/flutter (10656): <asynchronous suspension>
E/flutter (10656): #4      DioMixin._request._interceptorWrapper.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:dio/src/dio.dart)
E/flutter (10656): <asynchronous suspension>
E/flutter (10656): 
E/flutter (10656): #0      Sigepweb.calcPrecoPrazo (package:sigepweb/src/core.dart:177:7)
E/flutter (10656): <asynchronous suspension>
E/flutter (10656): #1      CartProductController.calculateDelivery (package:tofazenunada/controllers/cart.product.controller.dart:184:28)
E/flutter (10656): <asynchronous suspension>
E/flutter (10656):

**Comment by Mateusvaz89** [comment]
Estava funcionando normal até ontem..

**Comment by marcobraghim** [comment]
Olá Mateus, obrigado por abrir essa questão.

Isso está acontecendo porque o endpoint dos correios recebe HTTP apenas em vez de HTTPS, note no link abaixo onde é definido o protocolo

https://github.com/marcobraghim/sigepweb/blob/master/lib/src/core.dart#L87

Ao abrir no navegador o endpoint que está dando erro para você com HTTPS funciona [este aqui](https://ws.correios.com.br/calculador/CalcPrecoPrazo.asmx/CalcPrecoPrazo?nCdEmpresa=08082650&sDsSenha=564321&nCdServico=04014%2C04510&sCepOrigem=66053180&sCepDestino=68680000&nVlPeso=0.1&nCdFormato=1&nVlComprimento=16&nVlAltura=12&nVlLargura=16&nVlDiametro=0&sCdMaoPropria=N&nVlValorDeclarado=0.0&sCdAvisoRecebimento=S&StrRetorno=xml&nIndicaCalculo=3), isso pode significar que os correios liberaram SSL para este serviço e por isso eu preciso atualizar o package com isso, mas é dificil ter certeza. O mais rapido possível vou adicionar um fix para isso e deixar opcional o SSL ali, evitando assim que sistemas que estão funcionando sem o SSL parem de funcionar.

Fique a vontade para abrir um Pull-Request caso pense em uma solução mais viável.

**Comment by Mateusvaz89** [comment]
O que eu posso fazer pra resolver ?? pode ser uma pergunta boba, mas eu sou iniciante.

**Comment by marcobraghim** [comment]
A princípio basta trocar `http` por `https` naquela linha que te mandei, mas nao precisa fazer nada, eu vou subir uma atualização ainda hoje para isso. ;)

**Comment by marcobraghim** [comment]
@Mateusvaz89 Por favor teste a versão 1.0.8. Note que agora na instancia da classe voce pode informar se quer usar SSL ou nao. Isso deve resolver.

**Comment by marcobraghim** [comment]
Acabei de lançar a versao 2.0.0-beta com Null-Safety e testar inclusive esse problema. Todos os endpoints estao funcionando com SSL = FALSE então agora nao acho que esse fix vai te ajudar. Por favor mantenha-nos informados se ainda esta tendo problemas.

**Comment by Mateusvaz89** [comment]
Só fica dando throw na requisição 

![Captura de tela 2021-03-15 131007](https://user-images.githubusercontent.com/59057718/111184578-da0c7880-858f-11eb-8a9b-87d85d3645b8.jpg)

**Comment by Mateusvaz89** [comment]
![Captura de tela 2021-03-15 131235](https://user-images.githubusercontent.com/59057718/111184862-2788e580-8590-11eb-90f6-b01a86711593.jpg)

**Comment by marcobraghim** [comment]
Ta dando ali "Connection timeout" e isso vem dos correios. Pra gente entender de fato o que está havendo precisamos interceptar exatamente qual é a URL que está sendo chamada, tu consegue ver isso pra gente?

**Comment by Mateusvaz89** [comment]
tem hora que funciona e tem hora que não funciona

**Comment by marcobraghim** [comment]
> tem hora que funciona e tem hora que não funciona

Hummmmmm esse comportamento me parece instabilidade dos correios... É uma empresa `fantástica` assim mesmo... kkkkkk

Você está usando o package para obter endereço ou cálculo de frete?
