### ISSUE TITLE
Connection refused

### ISSUE THREAD

**Issue by SergioMordente** [marcobraghim/sigepweb#7]
Até semana passava funcionava bem, desde ontem esta com este erro. 
Sabe se mudou alguma coisa no endpoint ou exigência dos Correios?
I/flutter (26265): 124 Erro interno do package. Por favor considere abrir uma questão em https://github.com/marcobraghim/sigepweb/issues
I/flutter (26265): Mensagem da exception foi: DioError [DioErrorType.other]: SocketException: Connection refused (OS Error: Connection refused, errno = 111), address = ws.correios.com.br, port = 53832
I/flutter (26265): Source stack:
I/flutter (26265): #0      DioMixin.fetch (package:dio/src/dio_mixin.dart:488:35)
I/flutter (26265): #1      DioMixin.request (package:dio/src/dio_mixin.dart:483:12)
I/flutter (26265): #2      DioMixin.get (package:dio/src/dio_mixin.dart:61:12)
I/flutter (26265): #3      Sigepweb.calcPrecoPrazo (package:sigepweb/src/core.dart:99:28)
I/flutter (26265): #4      DeliveryPageState._calculaSedexPcd (package:photokiosk/views/delivery_page.dart:111:66)

**Comment by SergioMordente** [comment]
Completando informação: Versão 2.0.0-beta com Dart 3
